#!/bin/sh

show_help() {
	echo "Usage: $0 [ARGS]"
	echo "Installs the aether desktop environment."
	echo
	echo "Arguments:"
	echo -e "-u | --update \t Uses the newest version of all packages."
	echo -e "-h | --help \t Shows this help message."
}

prepare_system_config() {
	sudo mkdir -p /etc/aether/state

	sudo echo "{ ... }:
	{ 
		system.stateVersion = \"$NIXOS_VERSION\"; 
	}" | sudo tee /etc/aether/state/configuration.nix >> /dev/null

	sudo nixos-generate-config --dir /etc/aether/state

	if [ ! -e $CONFIG_PATH ]; then
		sudo mkdir -p $CONFIG_PATH

		sudo cp $SCRIPTPATH/system/defaults/users.nix $CONFIG_PATH/users.nix
		sudo sed -i "s|{{user}}|$USER|g" $CONFIG_PATH/users.nix
		sudo sed -i "s|{{username}}|$USERNAME|g" $CONFIG_PATH/users.nix

		sudo cp $SCRIPTPATH/system/defaults/config.nix $CONFIG_PATH/config.nix
		sudo sed -i "s|{{hostname}}|$(hostname)|g" $CONFIG_PATH/config.nix
	fi
}

apply_system_config() {
	if [[ $UPDATE == true ]]; then
		sudo rm -f /etc/aether/src/flake.lock
	fi

	sudo nixos-rebuild switch --flake $(readlink -f /etc/aether/src)/system/.#aether --impure
}

prepare_user_config() {
	if [ ! -e $USER_CONFIG_PATH ]; then
		mkdir -p $USER_CONFIG_PATH/modules

		cp /etc/aether/src/user/defaults/home-manager.nix $USER_CONFIG_PATH/modules/home-manager.nix
		sed -i "s|{{user}}|$USER|g" $USER_CONFIG_PATH/modules/home-manager.nix
		sed -i "s|{{home}}|$HOME|g" $USER_CONFIG_PATH/modules/home-manager.nix

		cp /etc/aether/src/user/defaults/config.nix $USER_CONFIG_PATH/config.nix
		cp /etc/aether/src/user/defaults/flake.nix $USER_CONFIG_PATH/flake.nix
	fi
}

apply_user_config() {
	if [[ $UPDATE == true ]]; then
		rm -f $USER_CONFIG_PATH/flake.lock
	fi

	aether apply 
}

set -e

if command -v aether-system >/dev/null 2>&1; then
	echo "Already installed";
	exit 1;
fi

UPDATE=false

for arg in $@; do
	case $arg in
		-u|--update)
			UPDATE=true
		;;
		-h|--help)
			show_help
			exit 0
		;;
		*)
			echo "Invalid argument $arg"
			exit 1
		;;
	esac
done

NIXOS_VERSION=$(nixos-version | head -c 5)
USERNAME=$(getent passwd $USER | cut -d: -f5)
SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
CONFIG_PATH=/etc/aether/config
USER_CONFIG_PATH=$HOME/.config/aether

sudo rm -rf /etc/nixos
sudo mkdir -p /etc/aether
sudo ln -s $SCRIPTPATH /etc/aether/src

prepare_system_config
prepare_user_config

apply_system_config
apply_user_config

echo "Instalation complete. Please, reboot the system."
